from django import forms

class student_reg(forms.Form):
    student_name=forms.CharField(max_length=50)
    student_DOB=forms.DateField()
    student_father=forms.CharField(max_length=50)
    student_mother=forms.CharField(max_length=50)
    student_category=forms.CharField(max_length=10)
    student_gender=forms.CharField(max_length=20)
    student_nationality=forms.CharField(max_length=20)
    student_domicile=forms.CharField(max_length=50)
    student_blood=forms.CharField(max_length=5)
    student_email=forms.EmailField()
    student_parent_email=forms.EmailField()
    student_ph=forms.IntegerField()
    student_father_ph=forms.IntegerField()
    student_aadhar=forms.IntegerField()
    student_corr_address1=forms.CharField(max_length=300)
    student_corr_address2=forms.CharField(max_length=300)
    student_corr_city=forms.CharField(max_length=50)
    student_corr_district=forms.CharField(max_length=50)
    student_corr_state=forms.CharField(max_length=50)
    student_corr_country=forms.CharField(max_length=50)
    student_corr_pincode=forms.IntegerField()
    student_par_address1=forms.CharField(max_length=300)
    student_par_address2=forms.CharField(max_length=300)
    student_par_city=forms.CharField(max_length=50)
    student_par_district=forms.CharField(max_length=50)
    student_par_state=forms.CharField(max_length=50)
    student_par_country=forms.CharField(max_length=50)
    student_par_pincode=forms.IntegerField()
    # student_image=forms.ImageField()
    student_course=forms.CharField(max_length=10)
    yes=forms.CharField(max_length=10)