# Generated by Django 2.2.12 on 2020-05-20 16:19

from django.db import migrations, models
import jsonfield.fields
import register.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fee_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_payable', models.IntegerField(blank=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('cheque_no', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_admission_status', models.CharField(default='pending', max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('student_DOB', models.DateField()),
                ('student_father', models.CharField(max_length=50)),
                ('student_mother', models.CharField(max_length=50)),
                ('student_category', models.CharField(max_length=10)),
                ('student_gender', models.CharField(max_length=20)),
                ('student_nationality', models.CharField(max_length=20)),
                ('student_domicile', models.CharField(max_length=50)),
                ('student_blood', models.CharField(max_length=5)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_parent_email', models.EmailField(max_length=254)),
                ('student_ph', models.BigIntegerField()),
                ('student_father_ph', models.BigIntegerField()),
                ('student_aadhar', models.BigIntegerField()),
                ('student_corr_address1', models.CharField(max_length=300)),
                ('student_corr_address2', models.CharField(max_length=300)),
                ('student_corr_city', models.CharField(max_length=50)),
                ('student_corr_district', models.CharField(max_length=50)),
                ('student_corr_state', models.CharField(max_length=50)),
                ('student_corr_country', models.CharField(max_length=50)),
                ('student_corr_pincode', models.IntegerField()),
                ('student_parr_address', models.CharField(max_length=300)),
                ('student_parraddress', models.CharField(max_length=300)),
                ('student_parrcity', models.CharField(max_length=50)),
                ('student_parrdistrict', models.CharField(max_length=50)),
                ('student_parrstate', models.CharField(max_length=50)),
                ('student_parrcountry', models.CharField(max_length=50)),
                ('student_parrpincode', models.IntegerField()),
                ('student_course', models.CharField(max_length=50)),
                ('student_batch', models.CharField(blank=True, max_length=50)),
                ('student_fee_pattern', models.CharField(blank=True, max_length=50)),
                ('student_image', models.CharField(max_length=100)),
                ('student_fee_deatils', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_image', models.ImageField(upload_to=register.models.upload_path)),
            ],
        ),
    ]
