# Generated by Django 3.0.4 on 2020-03-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_DOB', models.DateField()),
                ('student_father', models.CharField(max_length=50)),
                ('student_mother', models.CharField(max_length=50)),
                ('student_category', models.CharField(max_length=10)),
                ('student_gender', models.CharField(max_length=20)),
                ('student_nationality', models.CharField(max_length=20)),
                ('student_domicile', models.CharField(max_length=50)),
                ('student_blood', models.CharField(max_length=5)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_parent_email', models.EmailField(max_length=254)),
                ('student_ph', models.IntegerField(default='not given')),
                ('student_father_ph', models.IntegerField()),
                ('student_aadhar', models.IntegerField()),
                ('student_corr_address', models.CharField(max_length=300)),
                ('student_corr_city', models.CharField(max_length=50)),
                ('student_corr_district', models.CharField(max_length=50)),
                ('student_corr_state', models.CharField(max_length=50)),
                ('student_corr_country', models.CharField(max_length=50)),
                ('student_corr_pincode', models.IntegerField()),
                ('student_address', models.CharField(max_length=300)),
                ('student_city', models.CharField(max_length=50)),
                ('student_district', models.CharField(max_length=50)),
                ('student_state', models.CharField(max_length=50)),
                ('student_country', models.CharField(max_length=50)),
                ('student_pincode', models.IntegerField()),
                ('student_image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
