# Generated by Django 2.2.11 on 2020-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='student_academic_year',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='student_details',
            name='student_admission_category',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='student_details',
            name='student_admission_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='student_details',
            name='student_batch',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='student_details',
            name='student_fee_category',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
