# Generated by Django 3.0.4 on 2020-03-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200318_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='student_course',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
