# Generated by Django 2.2.12 on 2020-05-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200520_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='student_fee_deatils',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
