# Generated by Django 2.2.12 on 2020-05-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200520_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='student_fee_deatils',
        ),
    ]
