# Generated by Django 3.0.5 on 2020-04-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200411_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='student_image',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
