# Generated by Django 3.0.4 on 2020-03-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_student_details_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='student_image',
        ),
    ]
