# Generated by Django 3.0.4 on 2020-03-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_student_details_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='student_address',
            new_name='student_corr_address2',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='student_corr_address',
            new_name='student_parr_address',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='student_city',
            new_name='student_parrcity',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='student_country',
            new_name='student_parrcountry',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='student_district',
            new_name='student_parrdistrict',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='student_pincode',
            new_name='student_parrpincode',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='student_state',
            new_name='student_parrstate',
        ),
        migrations.AddField(
            model_name='student_details',
            name='student_parraddress',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
