# Generated by Django 2.2.12 on 2020-05-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_student_details_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='student_academic_year',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='student_admission_category',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='student_fee_category',
        ),
        migrations.AddField(
            model_name='student_details',
            name='student_fee_pattern',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='student_batch',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
