# Generated by Django 2.2.12 on 2020-05-20 16:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_student_details_student_fee_deatils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='student_fee_deatils',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
