# Generated by Django 3.0.4 on 2020-03-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200319_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='student_corr_address1',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
