# Generated by Django 2.2.12 on 2020-05-21 10:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200520_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='student_fee_mont_wise',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
