# Generated by Django 2.2.12 on 2020-05-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(),
        ),
    ]
