# Generated by Django 2.2.12 on 2020-05-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feepattern', '0002_auto_20200503_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePatternHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_pattern_name', models.CharField(max_length=50)),
                ('fee_collect_pattern', models.CharField(max_length=50)),
                ('total_academic_fee', models.CharField(max_length=50)),
                ('total_tution_fee', models.CharField(blank=True, max_length=50)),
                ('total_hostel_fee', models.CharField(max_length=50)),
            ],
        ),
    ]
